### ISSUE TITLE
change language in application content

### ISSUE THREAD

**Issue by nusrateka** [PhraseApp-Blog/electron-i18n#1]
I did the change from menu template but when I try to change Locale in the application content it does not show anything. It shows error in app.js file. the error is showing in this line: (t, { i18n }) => . it shows that i18n is defined but never used.  Can you help me please?

**Comment by theodesp** [comment]
i18n is unused and you can remove it. If you don't use any linter it won't complain. I will update the repo

**Comment by nusrateka** [comment]
Thank you for your reply.  There is another problem in main.js file, there is a line like `resource: i18n.getResourceBundle(lng, config.namespace)` . It shows that  **18n.getResourceBundle is not a function** .  Why it's showing this?
